# Generated by Django 5.0.14 on 2026-03-29 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Gider Başlığı')),
                ('expense_type', models.CharField(choices=[('ASANSOR', 'Asansör'), ('TEMIZLIK', 'Temizlik'), ('ELEKTRIK', 'Elektrik'), ('DIGER', 'Diğer')], max_length=20, verbose_name='Tür')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('date', models.DateField(auto_now_add=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Fatura / Makbuz')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Bakım Başlığı')),
                ('scheduled_date', models.DateField(verbose_name='Planlanan Tarih')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Daire Numarası')),
                ('type', models.CharField(choices=[('KONUT', 'Konut'), ('ISYERI', 'İş Yeri')], default='KONUT', max_length=15, verbose_name='Tür')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apartments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('due_date', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ödenme Tarihi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.apartment')),
            ],
        ),
    ]
