# Generated by Django 5.1.15 on 2026-03-29 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['number'], 'verbose_name': 'Daire', 'verbose_name_plural': 'Daireler'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Apartman Gideri', 'verbose_name_plural': 'Apartman Giderleri'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Bakım Kaydı', 'verbose_name_plural': 'Bakım Takvimi'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-due_date'], 'verbose_name': 'Ödeme/Aidat', 'verbose_name_plural': 'Ödemeler ve Aidatlar'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apartments', to=settings.AUTH_USER_MODEL, verbose_name='Ev Sahibi'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_apartments', to=settings.AUTH_USER_MODEL, verbose_name='Kiracı'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='type',
            field=models.CharField(choices=[('KONUT', 'Konut'), ('ISYERI', 'İş Yeri')], default='KONUT', max_length=15, verbose_name='Daire Türü'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('ASANSOR', 'Asansör'), ('TEMIZLIK', 'Temizlik'), ('ELEKTRIK', 'Elektrik'), ('DIGER', 'Diğer')], max_length=20, verbose_name='Gider Kategorisi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Fatura / Makbuz Resmi'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bakım Maliyeti'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Bakım Tamamlandı mı?'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Bakım Konusu (Örn: Asansör)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.apartment', verbose_name='Daire'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama / Ay Bilgisi'),
        ),
    ]
