# Generated by Django 5.1.15 on 2026-03-29 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apartment_options_alter_expense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('ACIK', 'Açık / İnceleniyor'), ('COZULDU', 'Çözüldü / Tamamlandı')], default='ACIK', max_length=20, verbose_name='Durum')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Şikayet ve Geri Bildirim',
                'verbose_name_plural': 'Şikayetler ve Geri Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
