# Generated by Django 5.1.15 on 2026-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='dues_amount',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10, verbose_name='Güncel Aidat Tutarı (TL)'),
        ),
    ]
