# Generated by Django 5.1.15 on 2026-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apartment_dues_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_dues_amount', models.DecimalField(decimal_places=2, default=450.0, max_digits=10, verbose_name='Genel Aidat Tutarı (TL)')),
            ],
            options={
                'verbose_name': 'Apartman Ayarı',
                'verbose_name_plural': 'Apartman Ayarları',
            },
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='dues_amount',
        ),
    ]
