# Generated by Django 5.1.15 on 2026-03-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_buildingsettings_remove_apartment_dues_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_distributed',
            field=models.BooleanField(default=False, verbose_name='Bölüştürme Yapıldı'),
        ),
        migrations.AddField(
            model_name='expense',
            name='should_distribute',
            field=models.BooleanField(default=False, verbose_name='Tüm Dairelere Borç Olarak Bölüştür'),
        ),
        migrations.AddField(
            model_name='payment',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='api.expense', verbose_name='Bağlı Gider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('AIDAT', 'Düzenli Aidat'), ('EK_ODEME', 'Ekstra Gider/Ödeme')], default='AIDAT', max_length=15, verbose_name='Ödeme Türü'),
        ),
    ]
