# Generated by Django 5.1.15 on 2026-03-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense_is_distributed_expense_should_distribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('YENI_AIDAT', 'Yeni Aidat Bilgilendirmesi'), ('HATIRLATMA', 'Son Ödeme Hatırlatması')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.apartment')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.payment')),
            ],
            options={
                'verbose_name': 'Bildirim Kaydı',
                'verbose_name_plural': 'Bildirim Kayıtları',
                'ordering': ['-sent_at'],
            },
        ),
    ]
